module.exports = {
  AUTH: "Auth",
  DEV: "dev",
  PRODUCTION: "production",
  DEVELOPMENT: "development",
  API: "/api/",
  V1: "v1/",
  VALIDATION_ERROR: "ValidationError",
  NOT_FOUND: "Not Found",
  CLOUDINARY_FOLDER: "projectImages",
  FINISH: "finish",
  ID: "_id",
  ROLE: "role",
  PASSWORD: "+password",
  GMAIL: "gmail",
  MAYA: "Maya",
  CASH: "Cash",
  USERS: "users",
  USER: "user",
  PRODUCTS: "products",
  PRODUCT: "product",
  TRANSACTIONS: "transactions",
  TRANSACTION: "transaction",
  INVENTORIES: "inventories",
  INVENTORY: "inventory",
};
